config/routes.rb
Rails.application.routes.draw do

  get "/", to: 'homepage#home', as: "root"
  resources :landlords
	resources :complaints
	root 'complaints#index'
  get "/pages/:page" => "pages#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complaint.rb
class Complaint < ApplicationRecord
	belongs_to :landlord, optional: true
end

app/models/landlord.rb
class Landlord < ApplicationRecord
	has_many :complaints
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    #@complaints = Complaint.all
    if params[:sort_by]
      @complaints = Complaint.all.sort_by{|d| d.send(params[:sort_by]) }
    else
      @complaints = Complaint.all
    end
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(complaint_params)
    @complaint.landlord = Landlord.find_or_create_by(:name => params[:complaint][:landlord_name])
    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:landlord_name, :address, :complaint, :complaintdate, :eviction_warning, :building_violation, :entered_wo_notice, :withhold_security_dep, :anti_complaints, :landlord_id)

    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def home
  end
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_action :set_landlord, only: [:show, :edit, :update, :destroy]

  # GET /landlords
  # GET /landlords.json
  def index
    #@landlords = Landlord.all
    if params[:sort_by]
      @landlords = Landlord.all.sort_by{|d| d.send(params[:sort_by]) }
    else
      @landlords = Landlord.all
    end
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
  end

  # GET /landlords/new
  def new
    @landlord = Landlord.new
  end

  # GET /landlords/1/edit
  def edit
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(landlord_params)

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to @landlord, notice: 'Landlord was successfully created.' }
        format.json { render :show, status: :created, location: @landlord }
      else
        format.html { render :new }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landlords/1
  # PATCH/PUT /landlords/1.json
  def update
    respond_to do |format|
      if @landlord.update(landlord_params)
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { render :show, status: :ok, location: @landlord }
      else
        format.html { render :edit }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
    @landlord.destroy
    respond_to do |format|
      format.html { redirect_to landlords_url, notice: 'Landlord was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landlord
      @landlord = Landlord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landlord_params
      params.require(:landlord).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/resources"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/complaints/_form.html.erb
<%= form_with(model: complaint, local: true) do |form| %>
  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% complaint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :landlord_name %>
    <%= form.text_field :landlord_name %>
  </div>

   <div class='field'>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class='field'>
    <%= form.label :complaint %>
    <%= form.text_field :complaint %>
  </div>

  <div class='field'>
    <%= form.label :complaint_date %>
    <%= form.date_field :complaintdate %>
  </div>

  <div class='field'>
    <%= form.label :eviction_warning, 'Was there an eviction warning?' %>
    <%= form.check_box :eviction_warning %>
  </div>

  <div class='field'>
    <%= form.label :building_violation, 'Was there a building violation?' %>
    <%= form.check_box :building_violation %>
  </div>

  <div class='field'>
    <%= form.label :entered_wo_notice, 'Did the landlord enter without notice?' %>
    <%= form.check_box :entered_wo_notice %>
  </div>

  <div class='field'>
    <%= form.label :withhold_security_dep, 'Did the landlord withhold the security deposit?' %>
    <%= form.check_box :withhold_security_dep %>
  </div>

  <div class='field'>
    <%= form.label :anti_complaints, 'Did the landlord retaliate against complaints?' %>
    <%= form.check_box :anti_complaints %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/complaints/edit.html.erb
<h1>Editing Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complaints</h1>

<p><h3><%= link_to 'Submit New Complaint', new_complaint_path %></h3></p>
<p><%= link_to 'Show All Landlords', landlords_path %></p>

<p><b>Sort:</b>
  <%= link_to "By Landlord Name", complaints_path(sort_by: :landlord_name) %>
</p>

<table>
  <thead>
    <tr>
      <th>Landlord name</th>
      <th>Address of building</th>
      <th>Nature of complaint</th>
      <th>Date of complaint</th>
      <th>Was there an eviction warning?</th>
      <th>Was there a building violation?</th>
      <th>Did the landlord enter without notice?</th>
      <th>Did the landlord withhold the security deposit?</th>
      <th>Did the landlord retaliate against complaints?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td align="center"><%= complaint.landlord_name %></td>
        <td align="center"><%= complaint.address %></td>
        <td align="center"><%= complaint.complaint %></td>
        <td align="center"><%= complaint.complaintdate %></td>
        <td align="center"><%= complaint.eviction_warning %></td>
        <td align="center"><%= complaint.building_violation %></td>
        <td align="center"><%= complaint.entered_wo_notice %></td>
        <td align="center"><%= complaint.withhold_security_dep %></td>
        <td align="center"><%= complaint.anti_complaints %></td>
        <!--<td align="center"><%= complaint.landlord.try(:name) %></td>-->
        <!-- <td><%= link_to 'Show', complaint %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3><%= link_to 'Submit New Complaint', new_complaint_path %></h3>

app/views/complaints/new.html.erb
<h1>New Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Back', complaints_path %>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Landlord name:</strong>
  <%= @complaint.landlord_name %>
</p>

<%= link_to 'Edit', edit_complaint_path(@complaint) %> |
<%= link_to 'Back', complaints_path %>

app/views/homepage/home.html.erb
  <!-- Masthead -->
  <header class="masthead text-white text-center" style="background-image: url(<%= asset_path 'tenant_protections_img.jpg' %>);">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">""</h1>
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
          <form>
            <div class="form-row">
              <div class="col-12 col-md-9 mb-2 mb-md-0">
              </div>
              <div class="col-12 col-md-3">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </header>

<div class="graphic-header about-us-hero center-page-wrapper">
  <div class="center-page">
    <h1 class="mb-5"> <center> Chicago Tenant Protection Project <center> </h1>
    <div class="underbar"></div>
  </div>
</div>

  <!-- Icons Grid -->
  <section class="features-icons bg-light text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-screen-desktop m-auto text-primary"></i>
            </div>
            <h3><%= link_to("Add Complaint/View Database", "/complaints") %></h3>
            <p class="lead mb-0">This database displays user-entered data about complaints against landlords in Chicago.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-layers m-auto text-primary"></i>
            </div>
            <h3><%= link_to("Tenant Resources", "/pages/Resources") %></h3>
            <p class="lead mb-0">Resources to file a formal complaint against a landlord/building and get legal help in Chicago.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-check m-auto text-primary"></i>
            </div>
            <h3><%= link_to("View List of Problematic Landlords", "/landlords") %></h3>
            <p class="lead mb-0">List of problematic landlords based on City of Chicago Data and data from our users.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Image Showcases -->
  <section class="showcase">
    <div class="container-fluid p-0">
      <div class="row no-gutters">

        <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url(<%= asset_path 'eviction_img.jpg' %>);"></div>
        <div class="col-lg-6 order-lg-1 my-auto showcase-text">
          <h2>About Us</h2>
          <p class="lead mb-0">The Chicago Tenant Protection Project collects and reports information on problematic landlords in the City of Chicago. Renters can report bad behavior to the city, but certain categories of behavior are not addressed.</p>
          <p class="lead mb-0">For example, while tenants can report building code violations, their only recourse for dealing with eviction notices is to go to court. There is no publicly accessible database that lists landlords who have attempted unfair evictions.</p>
          <p class="lead mb-0">This website aims to address this by providing an interface for tenants to submit complaints about their landlords, and view complaints submitted by others.</p>
        </div>
      </div>

app/views/landlords/_form.html.erb
<%= form_with(model: landlord, local: true) do |form| %>
  <% if landlord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(landlord.errors.count, "error") %> prohibited this landlord from being saved:</h2>

      <ul>
      <% landlord.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/landlords/edit.html.erb
<h1>Editing Landlord</h1>

<%= render 'form', landlord: @landlord %>

<%= link_to 'Show', @landlord %> |
<%= link_to 'Back', landlords_path %>

app/views/landlords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Landlords</h1>

<p><h3><%= link_to 'Show All Complaints', complaints_path %></h3></p>

<p><b>Sort:</b>
  <%= link_to "By Name", landlords_path(sort_by: :name) %>
</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Total number of complaints</th>
      <th>Number of eviction warning complaints</th>
      <th>Number of building violation complaints</th>
      <th>Number of entering without notice complaints</th>
      <th>Number of withholding security deposit complaints</th>
      <th>Number of anti-complaint complaints</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @landlords.each do |landlord| %>
      <tr>
        <td align="center"><%= landlord.name %></td>
        <td align="center"><%= landlord.complaints.count %></td>
        <td align="center"><%= landlord.complaints.where(eviction_warning: true).count %></td>
        <td align="center"><%= landlord.complaints.where(building_violation: true).count %></td>
        <td align="center"><%= landlord.complaints.where(entered_wo_notice: true).count %></td>
        <td align="center"><%= landlord.complaints.where(withhold_security_dep: true).count %></td>
        <td align="center"><%= landlord.complaints.where(anti_complaints: true).count %></td>
        <!--<td><%= link_to 'Show', landlord %></td>-->
        <!--<td><%= link_to 'Edit', edit_landlord_path(landlord) %></td>-->
        <!--<td><%= link_to 'Destroy', landlord, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Landlord', new_landlord_path %>

app/views/landlords/new.html.erb
<h1>New Landlord</h1>

<%= render 'form', landlord: @landlord %>

<%= link_to 'Back', landlords_path %>

app/views/landlords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @landlord.name %>
</p>

<%= link_to 'Edit', edit_landlord_path(@landlord) %> |
<%= link_to 'Back', landlords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>LandlordApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <a class="navbar-brand" href="#">LandlordApp</a>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/resources.html.erb
<body>
    <h2>Tenant Resources</h2>
    <hr>  <a class="" href="#"><%= link_to("Report a building code violation to the City", "https://311.chicago.gov/s/service-request?language=en_US") %></a>
    <hr>  <a class="" href="#"><%= link_to("14-day demand letter to landlord to make repairs", "https://www.illinoislegalaid.org/legal-information/14-day-demand-letter-landlord-make-repairs") %></a>
    <hr>  <a class="" href="#"><%= link_to("Know Your Rights - The Chicago Residential Landlord Tenant Ordinance", "https://bc-firm.com/tenants-rights-chicago/#2") %></a>
    <hr>  <a class="" href="#"><%= link_to("Free legal resources in Illinois by Zipcode", "https://www.illinoislegalaid.org/legal-information/helping-clients-landlord-and-tenant-cases") %></a>
    <hr>  <a class="" href="#"><%= link_to("Eviction Rate Map of Chicago from The Eviction Lab", "https://evictionlab.org/map/#/2016?geography=cities&bounds=-88.39,41.506,-86.948,42.105&type=er&locations=1714000,-87.732,41.834") %></a>

<body>